import { SERVICE_ID } from "../../common/enum";

const cf_info_INO = [
  // {
  //   name: 'GaliXCity',
  //   serviceID: SERVICE_ID._GALIXCITY,
  //   launch_date: 'September, 10 2022',
  //   launch_time: '11:00 UTC',
  //   status: 'ROUND 1 - Private',
  //   image_select: '1Select-Galix.png',
  //   image_selected: 'GaliXCity-select.png',
  //   startRound2: 1662390600,
  // character_image: require('../../assets/images/images_n69/mysterybox/logo/GaliXCity-select.png'),
  //   logoGame: require('../../assets/images/images_copy/games/galixcity.png'),
  //   image_select: require('../../assets/images/images_n69/mysterybox/1Select-Galix.png'),
  //   productBG: require('../../assets/images/images_n69/mysterybox/background/bg-big-select-mobile.png'),
  //   round: [
  //     {
  //       startTime: 0,
  //       endTime: 1662347400,
  //       name: 'Coming soon',
  //       class: '1',
  //     },
  //     {
  //       startTime: 1662347400,
  //       endTime: 1662390600,
  //       name: 'Round 1 - Private',
  //       class: '2',
  //     },
  //     {
  //       startTime: 1662390600,
  //       endTime: 1662477000,
  //       name: 'Round 2 - Public',
  //       class: '4',
  //     },
  //     {
  //       startTime: 1662477000,
  //       endTime: 9999999999,
  //       name: 'Closed',
  //       class: '5',
  //     },
  //   ],
  //   description:
  //     'Nuigurumi is a collection of delightfully cute friends living on the Solana network by artist and founder Rushmad. Our vision is to create a delightful family-friendly brand that anyone can enjoy in both the physical and digital worlds. Nuigurumi are universally loved characters who will bring out the values of kindness and bring joy to the world.',
  // },
  {
    name: "9DNFT",
    serviceID: SERVICE_ID._9DNFT,
    launch_date: "March, 21 2023",
    launch_time: "10:10 UTC+7",
    status: "ROUND 1 - Private",
    image_selected: "9DNFT-select.png",
    character_image: require("../../assets/images/images_n69/mysterybox/logo/9DNFT-select.png"),
    logoGame: require("../../assets/images/images_copy/games/9dnft.png"),
    image_select: require("../../assets/images/images_n69/mysterybox/1Select-9DNFT.png"),
    productBG: require("../../assets/images/images_n69/mysterybox/background/bg-big-select-mobile-9dnft.png"),
    startRound2: 1679458260,
    round: [
      {
        startTime: 0,
        endTime: 1679368200,
        name: "Coming soon",
        class: "1",
      },
      {
        startTime: 1679368200,
        endTime: 1679379000,
        name: "Round 1 - Private",
        class: "2",
      },
      {
        startTime: 1679379000,
        endTime: 1679454600,
        name: "Round 1 - Public",
        class: "2",
      },
      {
        startTime: 1679458260,
        endTime: 1679544660,
        name: "Round 2 - Public",
        class: "4",
      },
      {
        startTime: 1679544660,
        endTime: 9999999999,
        name: "Closed",
        class: "5",
      },
    ],
    description: `9D NFT is the first 3D Martial-Art Game of NFT Features in Southeast Asia and the first game project of Nemo Platform. An innovative NFTs project developed by a passionate team with many years of experience in the field of blockchain in general and virtual currency in particular. NFT Market with attractive features. Sharp graphic design, attractive gameplay with MMORPG genre. Unique gaming experience with many attractive incentives and a transparent monetary system. High security and safety. The Economy in the Game is Operated properly based on Automatic Mechanism in order to reserve. To ensure fairness for all players.`,
  },
  {
    name: "Mecha Warfare",
    serviceID: SERVICE_ID._MARSWAR,
    launch_date: "February, 16 2023",
    launch_time: "03:10 UTC",
    status: "ROUND 1 - Private",
    character_image: require("../../assets/images/images_n69/mysterybox/logo/MechaWarfare-select.png"),
    logoGame: require("../../assets/images/images_copy/games/mechawarfare.png"),
    image_select: require("../../assets/images/images_n69/mysterybox/1Select-Mecha.png"),
    productBG: require("../../assets/images/images_n69/mysterybox/background/bg-big-mobile-mecha.png"),
    image_selected: "Mecha Warfare-select.png",
    startRound2: 1676776200,
    round: [
      {
        startTime: 0,
        endTime: 1676517000,
        name: "Coming soon",
        class: "1",
      },
      {
        startTime: 1676517000,
        endTime: 1676527800,
        name: "Round 1 - Private",
        class: "2",
      },
      {
        startTime: 1676527800,
        endTime: 1676530800,
        name: "Next: Round 1 - Public",
        class: "2",
      },
      {
        startTime: 1676530800,
        endTime: 1676617200,
        name: "Round 1 - Public",
        class: "2",
      },
      {
        startTime: 1676617200,
        endTime: 1676689800,
        name: "Next: Round 2",
        class: "4",
      },
      {
        startTime: 1676689800,
        endTime: 1676776200,
        name: "Round 2",
        class: "4",
      },
      {
        startTime: 1676689800,
        endTime: 9999999999,
        name: "Closed",
        class: "5",
      },
    ],
    description: `In the world of Mecha Warfare, mankind has been evolving and striving hard for economic recovery after World War II. With their advanced tech, they have gradually attained the capacity to travel and live on Colonies (artificial asteroids). However, just as they felt leaving Earth was a harmless decision, Valeons, exotic species occupied in nearby asteroids have unexpectedly risen from their hibernation. How could mankind battle these strange beings? Let's wait and see their answers!`,
  },
  {
    name: "FlashPoint",
    serviceID: SERVICE_ID._FLASHPOINT,
    launch_date: "July 25, 2023",
    launch_time: "03:10 UTC",
    status: "ROUND 1 - Public",
    image_selected: "FlashPoint-select.png",
    character_image: require("../../assets/images/images_n69/mysterybox/logo/FlashPoint-select.png"),
    logoGame: require("../../assets/images/images_copy/games/flashpoint.png"),
    image_select: require("../../assets/images/images_n69/mysterybox/1Select-FlashPoint.png"),
    productBG: require("../../assets/images/images_n69/mysterybox/background/bg-big-select-mobile-flashpoint.png"),
    startRound2: 9999999999,
    round: [
      {
        startTime: 0,
        endTime: 1689563400,
        name: "Coming soon",
        class: "1",
      },
      {
        startTime: 1689563400,
        endTime: 1689649800,
        name: "Round 1 - Public",
        class: "2",
      },
      // {
      //   startTime: 1676527800,
      //   endTime: 1676530800,
      //   name: 'Next: Round 1 - Public',
      //   class: '2',
      // },
      // {
      //   startTime: 1676530800,
      //   endTime: 1676617200,
      //   name: 'Round 1 - Public',
      //   class: '2',
      // },
      // {
      //   startTime: 1676617200,
      //   endTime: 1676689800,
      //   name: 'Next: Round 2',
      //   class: '4',
      // },
      // {
      //   startTime: 1676689800,
      //   endTime: 1676776200,
      //   name: 'Round 2',
      //   class: '4',
      // },
      {
        startTime: 1689649800,
        endTime: 9999999999,
        name: "Closed",
        class: "5",
      },
    ],
    description: `FLASHPOINT: GUNFIGHT TO WIN NEMO is the first FPS game on the Play With Earn model. You will be able to choose from a variety of weapons and guns to take down your enemies. You can play alone or team up with friends to join other teams. The game has multiple modes including Team Mode, Blast Mode, Zombie Mode, Special Mode, and more. You can also customize your character with different skins and outfits.
      `,
  },
];

export default cf_info_INO;
