import { SERVICE_ID } from "../common/enum";
import { type IAssetDataNFT } from "../common/types";
import * as image from "../assets/images/images_n69/mywallet";

export const cf_assets_NFT: IAssetDataNFT[] = [
  // Galix
  {
    contractNamespace: "erc721_galix_resource",
    name: "Resource (GaliXcity)",
    symbol: "Resource",
    decimals: 1,
    icon: image.img_galix,
    icon_9d: image.img_galix,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    contractNamespace: "erc721_galix_hero",
    name: "Hero (GaliXcity)",
    symbol: "Hero",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    contractNamespace: "erc721_galix_land",
    name: "Land (GaliXcity)",
    symbol: "Land",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    contractNamespace: "erc721_galix_gbox",
    name: "Gold Box (GaliXcity)",
    symbol: "GBox",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    contractNamespace: "erc721_galix_pbox",
    name: "Platinum Box (GaliXcity)",
    symbol: "PBox",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    contractNamespace: "erc721_galix_dbox",
    name: "Diamond Box (GaliXcity)",
    symbol: "DBox",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  // 9DNFT
  {
    contractNamespace: "erc721_9dnft_hro",
    name: "Hero (9DNFT)",
    symbol: "Hero",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    contractNamespace: "erc721_9dnft_pet",
    name: "Pet (9DNFT)",
    symbol: "Pet",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    contractNamespace: "erc721_9dnft_petn",
    name: "PetN (9DNFT)",
    symbol: "PetN",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    contractNamespace: "erc721_9dnft_mnt",
    name: "MNT (9DNFT)",
    symbol: "MNT",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    contractNamespace: "erc721_9dnft_box",
    name: "Box (9DNFT)",
    symbol: "Box",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    contractNamespace: "erc721_9dnft_aeq",
    name: "Eqipment AEQ (9DNFT)",
    symbol: "AEQ",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    contractNamespace: "erc721_9dnft_oeq",
    name: "Eqipment OEQ (9DNFT)",
    symbol: "OEQ",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    contractNamespace: "erc721_9dnft_ueq",
    name: "Eqipment UEQ (9DNFT)",
    symbol: "UEQ",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    contractNamespace: "erc721_9dnft_gem",
    name: "Gem (9DNFT)",
    symbol: "Gem",
    decimals: 1,
    icon: image.img_nemo,
    icon_9d: image.img_nemo,
    serviceID: SERVICE_ID._9DNFT,
  },
];
