import { SERVICE_ID } from "../common/enum";
import { type ICollection } from "../common/types";
import * as icons from "../assets/images/images_copy/nft/icons";

export const cf_Collections_9DNFT: ICollection[] = [
  /// /
  {
    name: "9DNFT - Hero",
    symbol: "HRO",
    contractNamespace: "erc721_9dnft_hro",
    icon: icons.hro,
    slug: "hro",
    metadataNftType: "hro",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Pet",
    symbol: "PET",
    contractNamespace: "erc721_9dnft_pet",
    icon: icons.pet,
    slug: "pet",
    metadataNftType: "pet",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Petn",
    symbol: "PETN",
    contractNamespace: "erc721_9dnft_petn",
    icon: icons.pet,
    slug: "petn",
    metadataNftType: "petn",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Mount",
    symbol: "MNT",
    contractNamespace: "erc721_9dnft_mnt",
    icon: icons.mnt,
    slug: "mnt",
    metadataNftType: "mnt",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Box",
    symbol: "BOX",
    contractNamespace: "erc721_9dnft_box",
    icon: icons.box,
    slug: "box",
    metadataNftType: "box",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Star Equipment",
    symbol: "AEQ",
    contractNamespace: "erc721_9dnft_aeq",
    icon: icons.aeq,
    slug: "aeq",
    metadataNftType: "aeq",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Moon Equipment",
    symbol: "OEQ",
    contractNamespace: "erc721_9dnft_oeq",
    icon: icons.oeq,
    slug: "oeq",
    metadataNftType: "oeq",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Sun Equipment",
    symbol: "UEQ",
    contractNamespace: "erc721_9dnft_ueq",
    icon: icons.ueq,
    slug: "ueq",
    metadataNftType: "ueq",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Heaven Equipment",
    symbol: "HEQ",
    contractNamespace: "erc721_9dnft_heq",
    icon: icons.heq,
    slug: "heq",
    metadataNftType: "heq",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Material",
    symbol: "MAT",
    contractNamespace: "erc721_9dnft_mat",
    icon: icons.mat,
    slug: "mat",
    metadataNftType: "mat",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Gem",
    symbol: "GEM",
    contractNamespace: "erc721_9dnft_gem",
    icon: icons.gem,
    slug: "gem",
    metadataNftType: "gem",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },

  // INO MARKET
  {
    name: "9DNFT - HERO Box",
    symbol: "HRBX",
    contractNamespace: "erc721_9dnft_hrbx",
    icon: icons.aeq,
    slug: "hrbx",
    metadataNftType: "hrbx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - EPIC Box",
    symbol: "EPBX",
    contractNamespace: "erc721_9dnft_epbx",
    icon: icons.oeq,
    slug: "epbx",
    metadataNftType: "epbx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - LEGEND Box",
    symbol: "LEBX",
    contractNamespace: "erc721_9dnft_lebx",
    icon: icons.ueq,
    slug: "lebx",
    metadataNftType: "lebx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Dragon Box",
    symbol: "DGBX",
    contractNamespace: "erc721_9dnft_dgbx",
    icon: icons.mat,
    slug: "dgbx",
    metadataNftType: "dgbx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Master Box",
    symbol: "MTBX",
    contractNamespace: "erc721_9dnft_mtbx",
    icon: icons.gem,
    slug: "mtbx",
    metadataNftType: "mtbx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },

  // BOX STALING
  {
    name: "9DNFT - Silver Box",
    symbol: "SIBX",
    contractNamespace: "erc721_9dnft_sibx",
    icon: icons.aeq,
    slug: "sibx",
    metadataNftType: "sibx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Gold Box",
    symbol: "GOBX",
    contractNamespace: "erc721_9dnft_gobx",
    icon: icons.aeq,
    slug: "gobx",
    metadataNftType: "gobx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Platium Box",
    symbol: "PLBX",
    contractNamespace: "erc721_9dnft_plbx",
    icon: icons.aeq,
    slug: "plbx",
    metadataNftType: "plbx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Diamond Box",
    symbol: "DIBX",
    contractNamespace: "erc721_9dnft_dibx",
    icon: icons.aeq,
    slug: "dibx",
    metadataNftType: "dibx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Mystery Box",
    symbol: "MYBX",
    contractNamespace: "erc721_9dnft_mybx",
    icon: icons.aeq,
    slug: "mybx",
    metadataNftType: "mybx",
    isBurnToUse: true,
    serviceID: SERVICE_ID._9DNFT,
  },
  // INO
  {
    name: "9DNFT - Ancient Box",
    symbol: "ABOX",
    contractNamespace: "erc721_9dnft_abox",
    icon: icons.aeq,
    slug: "abox",
    isBurnToUse: false,
    serviceID: SERVICE_ID._9DNFT,
  },
  {
    name: "9DNFT - Divine Box",
    symbol: "DBOX",
    contractNamespace: "erc721_9dnft_dbox",
    icon: icons.aeq,
    slug: "dbox",
    isBurnToUse: false,
    serviceID: SERVICE_ID._9DNFT,
  },
];

export const cf_Collections_GalixCity: ICollection[] = [
  {
    name: "GaliXCity - Hero",
    symbol: "hro",
    contractNamespace: "erc721_galix_hero",
    slug: "hero",
    metadataNftType: "hero",
    isBurnToUse: true,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    name: "GaliXCity - Resource",
    symbol: "res",
    contractNamespace: "erc721_galix_resource",
    slug: "res",
    metadataNftType: "res",
    isBurnToUse: true,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    name: "GaliXCity - Land",
    symbol: "land",
    contractNamespace: "erc721_galix_land",
    slug: "land",
    metadataNftType: "land",
    isBurnToUse: false,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    name: "GaliXCity - Gold Box",
    symbol: "gbox",
    contractNamespace: "erc721_galix_gbox",
    slug: "gbox",
    metadataNftType: "box",
    isBurnToUse: false,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    name: "GaliXCity - Platinum Box",
    symbol: "pbox",
    contractNamespace: "erc721_galix_pbox",
    slug: "pbox",
    metadataNftType: "box",
    isBurnToUse: false,
    serviceID: SERVICE_ID._GALIXCITY,
  },
  {
    name: "GaliXCity - Diamond Box",
    symbol: "dbox",
    contractNamespace: "erc721_galix_dbox",
    slug: "dbox",
    metadataNftType: "box",
    isBurnToUse: false,
    serviceID: SERVICE_ID._GALIXCITY,
  },
];

export const cf_Collections_FlashPoint: ICollection[] = [
  {
    name: "Flashpoint - Weapon",
    symbol: "wea",
    contractNamespace: "erc721_flashpoint_weapon",
    slug: "nweapon",
    metadataNftType: "weapon",
    isBurnToUse: true,
    serviceID: SERVICE_ID._FLASHPOINT,
  },
  {
    name: "Flashpoint - Bronze Assault Box",
    symbol: "babox",
    contractNamespace: "erc721_flashpoint_babox",
    slug: "babox",
    metadataNftType: "Box",
    isBurnToUse: false,
    serviceID: SERVICE_ID._FLASHPOINT,
  },
  {
    name: "Flashpoint - Golden Arsenal Box",
    symbol: "gabox",
    contractNamespace: "erc721_flashpoint_gabox",
    slug: "gabox",
    metadataNftType: "Box",
    isBurnToUse: false,
    serviceID: SERVICE_ID._FLASHPOINT,
  },
  {
    name: "Flashpoint - Platinum Power Box",
    symbol: "ppbox",
    contractNamespace: "erc721_flashpoint_ppbox",
    slug: "ppbox",
    metadataNftType: "Box",
    isBurnToUse: false,
    serviceID: SERVICE_ID._FLASHPOINT,
  },
];

export const cf_Collections_Spirit: ICollection[] = [
  /// /
  {
    name: "Soul Realm - Pet",
    symbol: "N36PET",
    contractNamespace: "erc721_soulrealm_n36pet",
    icon: icons.pet,
    slug: "n36pet",
    metadataNftType: "n36pet",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Petn",
    symbol: "N36PEG",
    contractNamespace: "erc721_soulrealm_n36peg",
    icon: icons.pet,
    slug: "n36peg",
    metadataNftType: "n36peg",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Materials",
    symbol: "N36MAT",
    contractNamespace: "erc721_soulrealm_n36mat",
    icon: icons.mnt,
    slug: "n36mat",
    metadataNftType: "n36mat",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Box",
    symbol: "N36BOX",
    contractNamespace: "erc721_soulrealm_n36box",
    icon: icons.box,
    slug: "n36box",
    metadataNftType: "n36box",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Star Equipment",
    symbol: "N36YEQ",
    contractNamespace: "erc721_soulrealm_n36yeq",
    icon: icons.aeq,
    slug: "n36yeq",
    metadataNftType: "n36yeq",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Moon Equipment",
    symbol: "n36oeq",
    contractNamespace: "erc721_soulrealm_n36oeq",
    icon: icons.oeq,
    slug: "n36oeq",
    metadataNftType: "n36oeq",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Sun Equipment",
    symbol: "N36REQ",
    contractNamespace: "erc721_soulrealm_n36req",
    icon: icons.ueq,
    slug: "n36req",
    metadataNftType: "n36req",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Heaven Equipment",
    symbol: "N36PEQ",
    contractNamespace: "erc721_soulrealm_n36peq",
    icon: icons.heq,
    slug: "n36peq",
    metadataNftType: "n36peq",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Materials",
    symbol: "N36MAT",
    contractNamespace: "erc721_soulrealm_n36mat",
    icon: icons.mat,
    slug: "n36mat",
    metadataNftType: "n36mat",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Gem",
    symbol: "N36GEM",
    contractNamespace: "erc721_soulrealm_n36gem",
    icon: icons.gem,
    slug: "n36gem",
    metadataNftType: "n36gem",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
  {
    name: "Soul Realm - Fashion",
    symbol: "N36FSH",
    contractNamespace: "erc721_soulrealm_n36fsh",
    icon: icons.gem,
    slug: "n36fsh",
    metadataNftType: "n36fsh",
    isBurnToUse: true,
    serviceID: SERVICE_ID._SOUL_REALM,
  },
];

export const cf_Collections_Marswar: ICollection[] = [
  /// /
  {
    name: "Mecha Warfare - Hero",
    symbol: "N81HRO",
    contractNamespace: "erc721_marswar_n81hro",
    icon: icons.pet,
    slug: "hero",
    metadataNftType: "hero",
    isBurnToUse: true,
    serviceID: SERVICE_ID._MARSWAR,
  },
  {
    name: "Mecha Warfare - Petn",
    symbol: "N81WEP",
    contractNamespace: "erc721_marswar_n81wep",
    icon: icons.pet,
    slug: "equipment",
    metadataNftType: "equipment",
    isBurnToUse: true,
    serviceID: SERVICE_ID._MARSWAR,
  },
  {
    name: "Mecha Warfare - Materials",
    symbol: "N81GNR",
    contractNamespace: "erc721_marswar_n81gnr",
    icon: icons.mnt,
    slug: "common",
    metadataNftType: "common",
    isBurnToUse: true,
    serviceID: SERVICE_ID._MARSWAR,
  },
  {
    name: "Mecha Warfare - Mechanic Box",
    symbol: "N81MBOX",
    contractNamespace: "erc721_mecha_warfare_mbox",
    icon: icons.mnt,
    slug: "n81mbox",
    metadataNftType: "mystery box",
    isBurnToUse: false,
    serviceID: SERVICE_ID._MARSWAR,
  },
  {
    name: "Mecha Warfare - Prime Box",
    symbol: "N81PBOX",
    contractNamespace: "erc721_mecha_warfare_pbox",
    icon: icons.mnt,
    slug: "n81pbox",
    metadataNftType: "mystery box",
    isBurnToUse: false,
    serviceID: SERVICE_ID._MARSWAR,
  },
  {
    name: "Mecha Warfare - Supreme Box",
    symbol: "N81SBOX",
    contractNamespace: "erc721_mecha_warfare_sbox",
    icon: icons.mnt,
    slug: "n81sbox",
    metadataNftType: "mystery box",
    isBurnToUse: false,
    serviceID: SERVICE_ID._MARSWAR,
  },
];

export const cf_Collections_Naruto: ICollection[] = [
  /// /
  {
    name: "Naruto - Pet",
    symbol: "N33PET",
    contractNamespace: "erc721_naruto_n33pet",
    icon: icons.pet,
    slug: "n33pet",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
  {
    name: "Naruto - Petn",
    symbol: "N33PEG",
    contractNamespace: "erc721_naruto_n33peg",
    icon: icons.pet,
    slug: "n33peg",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
  {
    name: "Naruto - Materials",
    symbol: "N33MAT",
    contractNamespace: "erc721_naruto_n33mat",
    icon: icons.mnt,
    slug: "n33mat",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
  {
    name: "Naruto - Box",
    symbol: "N33BOX",
    contractNamespace: "erc721_naruto_n33box",
    icon: icons.box,
    slug: "n33box",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
  {
    name: "Naruto - Moon Equipment",
    symbol: "N33oeq",
    contractNamespace: "erc721_naruto_n33oeq",
    icon: icons.oeq,
    slug: "n33oeq",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
  {
    name: "Naruto - Sun Equipment",
    symbol: "N33REQ",
    contractNamespace: "erc721_naruto_n33req",
    icon: icons.ueq,
    slug: "n33req",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
  {
    name: "Naruto - Heaven Equipment",
    symbol: "N33PEQ",
    contractNamespace: "erc721_naruto_n33peq",
    icon: icons.heq,
    slug: "n33peq",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
  {
    name: "Naruto - Materials",
    symbol: "N33MAT",
    contractNamespace: "erc721_naruto_n33mat",
    icon: icons.mat,
    slug: "n33mat",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
  {
    name: "Naruto - Gem",
    symbol: "N33GEM",
    contractNamespace: "erc721_naruto_n33gem",
    icon: icons.gem,
    slug: "n33gem",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
  {
    name: "Naruto - Fashion",
    symbol: "N33FSH",
    contractNamespace: "erc721_naruto_n33fsh",
    icon: icons.gem,
    slug: "n33fsh",
    isBurnToUse: true,
    serviceID: SERVICE_ID._NARUTO,
  },
];

export const cf_Collections_RichworkFarmFamily: ICollection[] = [
  /// /
  {
    name: "RichworkFarmFamily - Dream Farm",
    symbol: "Dream Farm",
    contractNamespace: "erc721_richworkfarmfamily_fadr",
    icon: icons.pet,
    slug: "fadr",
    isBurnToUse: true,
    serviceID: SERVICE_ID._RICHWORK_FARM_FAMILY,
  },
  {
    name: "RichworkFarmFamily - Farm Tycoon",
    symbol: "Farm Tycoon",
    contractNamespace: "erc721_richworkfarmfamily_faty",
    icon: icons.pet,
    slug: "faty",
    isBurnToUse: true,
    serviceID: SERVICE_ID._RICHWORK_FARM_FAMILY,
  },
  {
    name: "RichworkFarmFamily - Fruit Farmer",
    symbol: "Fruit Farmer",
    contractNamespace: "erc721_richworkfarmfamily_faff",
    icon: icons.pet,
    slug: "faff",
    isBurnToUse: true,
    serviceID: SERVICE_ID._RICHWORK_FARM_FAMILY,
  },
  {
    name: "RichworkFarmFamily - Hyper Harvester",
    symbol: "Hyper Harvester",
    contractNamespace: "erc721_richworkfarmfamily_fahh",
    icon: icons.pet,
    slug: "fahh",
    isBurnToUse: true,
    serviceID: SERVICE_ID._RICHWORK_FARM_FAMILY,
  },
  {
    name: "RichworkFarmFamily - Land Owner ",
    symbol: "Land Owner ",
    contractNamespace: "erc721_richworkfarmfamily_falo",
    icon: icons.pet,
    slug: "falo",
    isBurnToUse: true,
    serviceID: SERVICE_ID._RICHWORK_FARM_FAMILY,
  },
];

export const cf_Collections_ScanRoot: ICollection[] = [
  /// /
  {
    name: "Scan Root NFT",
    symbol: "NFT",
    contractNamespace: "erc721_scanroot_nft",
    icon: icons.pet,
    slug: "srnft",
    isBurnToUse: true,
    serviceID: SERVICE_ID._OPS_ALPHA,
  },
];

export const Collections: ICollection[] = [
  ...cf_Collections_9DNFT,
  ...cf_Collections_GalixCity,
  ...cf_Collections_Spirit,
  ...cf_Collections_Marswar,
  ...cf_Collections_Naruto,
  ...cf_Collections_FlashPoint,
  ...cf_Collections_RichworkFarmFamily,
  ...cf_Collections_ScanRoot,
];
