import { type IRuleMystery } from "../common/types";

const cf_rules_mysteryinfo: IRuleMystery[] = [
  {
    levelMys: "Level 1",
    totalLevelLand: "1",
    rate_SSS: "0.5%",
    rate_S: "2.50%",
    rate_A: "7%",
    rate_B: "12%",
    rate_C: "28%",
    rate_D: "50%",
    cooldown: "86400",
  },
  {
    levelMys: "Level 2",
    totalLevelLand: "2",
    rate_SSS: "1%",
    rate_S: "3%",
    rate_A: "9%",
    rate_B: "15%",
    rate_C: "30%",
    rate_D: "42%",
    cooldown: "64800",
  },
  {
    levelMys: "Level 3",
    totalLevelLand: "3",
    rate_SSS: "1.5%",
    rate_S: "5.5%",
    rate_A: "11%",
    rate_B: "19%",
    rate_C: "28%",
    rate_D: "35%",
    cooldown: "51840",
  },
  {
    levelMys: "Level 4",
    totalLevelLand: "4",
    rate_SSS: "2%",
    rate_S: "8%",
    rate_A: "16%",
    rate_B: "26%",
    rate_C: "24%",
    rate_D: "24%",
    cooldown: "43200",
  },
  {
    levelMys: "Level 5",
    totalLevelLand: "5",
    rate_SSS: "3%",
    rate_S: "10%",
    rate_A: "22%",
    rate_B: "30%",
    rate_C: "19%",
    rate_D: "16%",
    cooldown: "37028",
  },
  {
    levelMys: "Level 6",
    totalLevelLand: "6",
    rate_SSS: "4%",
    rate_S: "14%",
    rate_A: "28%",
    rate_B: "28%",
    rate_C: "14%",
    rate_D: "12%",
    cooldown: "32400",
  },
  {
    levelMys: "Level 7",
    totalLevelLand: "7",
    rate_SSS: "5%",
    rate_S: "19%",
    rate_A: "29%",
    rate_B: "26%",
    rate_C: "12%",
    rate_D: "9%",
    cooldown: "28800",
  },
  {
    levelMys: "Level 8",
    totalLevelLand: "8",
    rate_SSS: "6%",
    rate_S: "22%",
    rate_A: "32%",
    rate_B: "24%",
    rate_C: "10%",
    rate_D: "6%",
    cooldown: "25920",
  },
  {
    levelMys: "Level 9",
    totalLevelLand: "9",
    rate_SSS: "6.5%",
    rate_S: "24%",
    rate_A: "34%",
    rate_B: "22%",
    rate_C: "8%",
    rate_D: "5.5%",
    cooldown: "23563",
  },
  {
    levelMys: "Level 10",
    totalLevelLand: "10",
    rate_SSS: "7%",
    rate_S: "25%",
    rate_A: "35%",
    rate_B: "20%",
    rate_C: "8%",
    rate_D: "5%",
    cooldown: "21600",
  },
];

export default cf_rules_mysteryinfo;
