import { type IAssetMysBox } from "../../../common/types";

const cf_rewards_mysterybox: IAssetMysBox[] = [
  {
    symbol: "GBOX",
    reward: [
      {
        type: "Hero",
        name: "Hero",
        rarity: "SSS",
        ratio: "0.11%",
        amount: "1",
        image: require("../../../assets/images/images_n69/Hero/SSS.png"),
      },
      {
        type: "Hero",
        name: "Hero",
        rarity: "S",
        ratio: "6.22%",
        amount: "56",
        image: require("../../../assets/images/images_n69/Hero/S.png"),
      },
      {
        type: "Hero",
        name: "Hero",
        rarity: "A",
        ratio: "14.44%",
        amount: "130",
        image: require("../../../assets/images/images_n69/Hero/A.png"),
      },
      {
        type: "Hero",
        name: "Hero",
        rarity: "B",
        ratio: "26%",
        amount: "150",
        image: require("../../../assets/images/images_n69/Hero/B.png"),
      },
      {
        type: "Hero",
        name: "Hero",
        rarity: "C",
        ratio: "44.44%",
        amount: "225",
        image: require("../../../assets/images/images_n69/Hero/C.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 5",
        ratio: "0.11%",
        amount: "1",
        image: require("../../../assets/images/images_n69/Land/Land_Level_5.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 4",
        ratio: "0.22%",
        amount: "2",
        image: require("../../../assets/images/images_n69/Land/Land_Level_4.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 3",
        ratio: "0.67%",
        amount: "6",
        image: require("../../../assets/images/images_n69/Land/Land_Level_3.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 2",
        ratio: "1.11%",
        amount: "10",
        image: require("../../../assets/images/images_n69/Land/Land_Level_2.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 1",
        ratio: "6.67%",
        amount: "60",
        image: require("../../../assets/images/images_n69/Land/Land_Level_1.png"),
      },
    ],
  },
  {
    symbol: "PBOX",
    reward: [
      {
        type: "Hero",
        name: "Hero",
        rarity: "SSS",
        ratio: "1%",
        amount: "8",
        image: require("../../../assets/images/images_n69/Hero/SSS.png"),
      },
      {
        type: "Hero",
        name: "Hero",
        rarity: "S",
        ratio: "6%",
        amount: "48",
        image: require("../../../assets/images/images_n69/Hero/S.png"),
      },
      {
        type: "Hero",
        name: "Hero",
        rarity: "A",
        ratio: "27%",
        amount: "216",
        image: require("../../../assets/images/images_n69/Hero/A.png"),
      },
      {
        type: "Hero",
        name: "Hero",
        rarity: "B",
        ratio: "31.5%",
        amount: "252",
        image: require("../../../assets/images/images_n69/Hero/B.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 5",
        ratio: "1.5%",
        amount: "6",
        image: require("../../../assets/images/images_n69/Land/Land_Level_5.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 4",
        ratio: "3%",
        amount: "12",
        image: require("../../../assets/images/images_n69/Land/Land_Level_4.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 3",
        ratio: "5.5%",
        amount: "22",
        image: require("../../../assets/images/images_n69/Land/Land_Level_3.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 2",
        ratio: "5%",
        amount: "20",
        image: require("../../../assets/images/images_n69/Land/Land_Level_2.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 1",
        ratio: "19.5%",
        amount: "78",
        image: require("../../../assets/images/images_n69/Land/Land_Level_1.png"),
      },
    ],
  },
  {
    symbol: "DBOX",
    reward: [
      {
        type: "Hero",
        name: "Hero",
        rarity: "SSS",
        ratio: "3%",
        amount: "24",
        image: require("../../../assets/images/images_n69/Hero/SSS.png"),
      },
      {
        type: "Hero",
        name: "Hero",
        rarity: "S",
        ratio: "8%",
        amount: "64",
        image: require("../../../assets/images/images_n69/Hero/S.png"),
      },
      {
        type: "Hero",
        name: "Hero",
        rarity: "A",
        ratio: "13%",
        amount: "104",
        image: require("../../../assets/images/images_n69/Hero/A.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 6",
        ratio: "0.5%",
        amount: "1",
        image: require("../../../assets/images/images_n69/Land/Land_Level_6.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 5",
        ratio: "7.5%",
        amount: "15",
        image: require("../../../assets/images/images_n69/Land/Land_Level_5.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 4",
        ratio: "15%",
        amount: "30",
        image: require("../../../assets/images/images_n69/Land/Land_Level_4.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 3",
        ratio: "20%",
        amount: "40",
        image: require("../../../assets/images/images_n69/Land/Land_Level_3.png"),
      },
      {
        type: "Land",
        name: "Land",
        rarity: "Level 2",
        ratio: "33%",
        amount: "66",
        image: require("../../../assets/images/images_n69/Land/Land_Level_2.png"),
      },
    ],
  },
];

export default cf_rewards_mysterybox;
