import { type IAssetMysBox } from "../../../common/types";

const cf_rewards_mysterybox_flashpoint: IAssetMysBox[] = [
  {
    symbol: "BABOX",
    reward: [
      {
        type: "Weapon",
        name: "NFT With Green Quality",
        ratio: "60%",
        rarity: "Green",
        amount: "1",
        image: require("../../../assets/images/images_n69/mysterybox/NFT_FLASHPOINT/NFT_With_Green_Quality.png"),
      },
      {
        type: "Weapon",
        name: "NFT With Blue Quality",
        ratio: "30%",
        rarity: "Blue",
        amount: "1",
        image: require("../../../assets/images/images_n69/mysterybox/NFT_FLASHPOINT/NFT_With_Blue_Quality.png"),
      },
      {
        type: "Weapon",
        name: "NFT With Purple Quality",
        ratio: "10%",
        rarity: "Violet",
        amount: "1",
        image: require("../../../assets/images/images_n69/mysterybox/NFT_FLASHPOINT/NFT_With_Purple_Quality.png"),
      },
      // {
      //   type: 'Weapon',
      //   name: 'AK47-The Bengaler (NFT)',
      //   ratio: '10%',
      //   rarity: 'Red',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'M4A1-Hunter Fury (NFT)',
      //   ratio: '10%',
      //   rarity: 'Red',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'P90-POMERANIAN (NFT)',
      //   ratio: '10%',
      //   rarity: 'Red',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'XM1014-CAMO (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'MP5-CAMO (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'M249-CAMO (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'DE-BLUE (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'AWP-BLUE (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'R8-DRAGON LI (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'R8-DRAGON LI (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
    ],
  },
  {
    symbol: "GABOX",
    reward: [
      {
        type: "Weapon",
        name: "NFT With Purple Quality",
        ratio: "40%",
        rarity: "Violet",
        amount: "1",
        image: require("../../../assets/images/images_n69/mysterybox/NFT_FLASHPOINT/NFT_With_Purple_Quality.png"),
      },
      {
        type: "Weapon",
        name: "NFT With Orange Quality",
        ratio: "60%",
        rarity: "Orange",
        amount: "1",
        image: require("../../../assets/images/images_n69/mysterybox/NFT_FLASHPOINT/NFT_With_Orange_Quality.png"),
      },
      // {
      //   type: 'Weapon',
      //   name: 'AK47–LUNAR SPECIAL (NFT)',
      //   ratio: '10%',
      //   rarity: 'Red',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'M4A1-DRAGON BONE (NFT)',
      //   ratio: '10%',
      //   rarity: 'Red',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'XM1014-DRAGON BONE (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'LUNAR GRENADE (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'GOLDEN AWP (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'GOLDEN AUG (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'GOLDEN FAMAS (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'GOLDEN MG3 (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'GOLDEN SIG552 (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'GOLDEN UMP45 (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
    ],
  },
  {
    symbol: "PPBOX",
    reward: [
      {
        type: "Weapon",
        name: "NFT With Orange Quality",
        ratio: "30%",
        rarity: "Orange",
        amount: "1",
        image: require("../../../assets/images/images_n69/mysterybox/NFT_FLASHPOINT/NFT_With_Orange_Quality.png"),
      },
      {
        type: "Weapon",
        name: "NFT With Gold Quality",
        ratio: "70%",
        rarity: "Yellow",
        amount: "1",
        image: require("../../../assets/images/images_n69/mysterybox/NFT_FLASHPOINT/NFT_With_Gold_Quality.png"),
      },
      // {
      //   type: 'Weapon',
      //   name: 'GOLDEN NEPAL SABER (NFT)',
      //   ratio: '10%',
      //   rarity: 'Red',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'GOLDEN SCAR (NFT)',
      //   ratio: '10%',
      //   rarity: 'Red',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'M4A1-SS-GOLDEN (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'MGX-HAVOC (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'LOOSE CANNON (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'AK47-GHOSTBANE (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'SIDEKICK (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: `GAMER'S GADGET (NFT)`,
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
      // {
      //   type: 'Weapon',
      //   name: 'DE–DRAGON SCALE (NFT)',
      //   rarity: 'Red',
      //   ratio: '10%',
      //   amount: '1',
      // },
    ],
  },
];

export default cf_rewards_mysterybox_flashpoint;
